### ISSUE TITLE
jsi command produces incorrect fromJson Method

### ISSUE THREAD

**Issue by Johannes5000** [DanWlker/dart-json-serializable-helper#1]
When using the jsi-command in VS Code, the fromJson method name is missing a "_" at the beginning.
![image](https://github.com/DanWlker/dart-json-serializable-helper/assets/61516197/ff86cbda-0115-48b5-84fd-e297d23b1ceb)

**Comment by DanWlker** [comment]
Hi sorry let me look into this

**Comment by DanWlker** [comment]
Hi I just pushed a version, can you try updating the extension to 1.0.7 and let me know if you still experience it? Thanks

**Comment by Johannes5000** [comment]
Looks good, thanks :)
